#define BATTLETOWER_PARTY_LENGTH 3
#define BATTLETOWER_STREAK_LENGTH 7

#define BATTLETOWER_NUM_UNIQUE_MON 21
#define BATTLETOWER_NUM_UNIQUE_TRAINERS 70

#define BATTLETOWER_TRAINERDATALENGTH (18 * 2)                                                                                             // 0x24
#define BATTLE_TOWER_STRUCT_LENGTH (NAME_LENGTH + BATTLETOWER_PARTY_LENGTH * NICKNAMED_MON_STRUCT_LENGTH + BATTLETOWER_TRAINERDATALENGTH)  // 0xe0

// BattleTowerAction setval arguments (see engine/events/battle_tower/battle_tower.asm)
enum {
    BATTLETOWERACTION_CHECK_EXPLANATION_READ,
    BATTLETOWERACTION_SET_EXPLANATION_READ,
    BATTLETOWERACTION_GET_CHALLENGE_STATE,
    BATTLETOWERACTION_SAVE_AND_QUIT,
    BATTLETOWERACTION_CHALLENGECANCELED,
    BATTLETOWERACTION_05,
    BATTLETOWERACTION_06,  // reset stuff in SRAM bank 5
    BATTLETOWERACTION_SAVELEVELGROUP,
    BATTLETOWERACTION_LOADLEVELGROUP,
    BATTLETOWERACTION_CHECKSAVEFILEISYOURS,
    BATTLETOWERACTION_0A,
    BATTLETOWERACTION_CHECKMOBILEEVENT,
    BATTLETOWERACTION_0C,  // more time stuff in SRAM bank 5
    BATTLETOWERACTION_0D,  // more time stuff in SRAM bank 5
    BATTLETOWERACTION_EGGTICKET,
    BATTLETOWERACTION_0F,  // check w3_d090
    BATTLETOWERACTION_10,  // dw based on s5_a800
    BATTLETOWERACTION_11,  // store 0 in s5_aa8d
    BATTLETOWERACTION_12,  // store 1 in s5_aa8d
    BATTLETOWERACTION_13,  // check s5_aa8d
    BATTLETOWERACTION_14,  // if save file is yours: bit 0, [sBattleTowerSaveFileFlags]
    BATTLETOWERACTION_15,  // set 0, [sBattleTowerSaveFileFlags]
    BATTLETOWERACTION_16,  // update time in SRAM bank 5
    BATTLETOWERACTION_17,  // check time in SRAM bank 5
    BATTLETOWERACTION_LEVEL_CHECK,
    BATTLETOWERACTION_UBERS_CHECK,
    BATTLETOWERACTION_RESETDATA,     // clear data
    BATTLETOWERACTION_GIVEREWARD,    // give reward
    BATTLETOWERACTION_1C,            // set won challenge
    BATTLETOWERACTION_1D,            // set received reward
    BATTLETOWERACTION_CHOOSEREWARD,  // save options
    BATTLETOWERACTION_SAVEOPTIONS,
};

// BattleTowerAction return values
// - from BATTLETOWERACTION_CHECKMOBILEEVENT
#define MOBILE_EVENT_OBJECT_GS_BALL 0xb

// BattleTowerText arguments (see engine/events/battle_tower/trainer_text.asm)
enum {
    BATTLETOWERTEXT_INTRO = 1,
    BATTLETOWERTEXT_WIN_TEXT,
    BATTLETOWERTEXT_LOSS_TEXT,
};

// sBattleTowerChallengeState values
enum {
    BATTLETOWER_NO_CHALLENGE,
    BATTLETOWER_SAVED_AND_LEFT,
    BATTLETOWER_CHALLENGE_IN_PROGRESS,
    BATTLETOWER_WON_CHALLENGE,
    BATTLETOWER_RECEIVED_REWARD,
};
