// pokemon ids
// indexes for:
// - PokemonNames (see data/pokemon/names.asm)
// - BaseData (see data/pokemon/base_stats.asm)
// - EvosAttacksPointers (see data/pokemon/evos_attacks_pointers.asm)
// - EggMovePointers (see data/pokemon/egg_move_pointers.asm)
// - PokemonCries (see data/pokemon/cries.asm)
// - MonMenuIcons (see data/pokemon/menu_icons.asm)
// - PokemonPicPointers (see data/pokemon/pic_pointers.asm)
// - PokemonPalettes (see data/pokemon/palettes.asm)
// - PokedexDataPointerTable (see data/pokemon/dex_entry_pointers.asm)
// - AlphabeticalPokedexOrder (see data/pokemon/dex_order_alpha.asm)
// - NewPokedexOrder (see data/pokemon/dex_order_new.asm)
// - Pokered_MonIndices (see data/pokemon/gen1_order.asm)
// - Footprints (see gfx/footprints.asm)
// - AnimationPointers (see gfx/pokemon/anim_pointers.asm)
// - AnimationIdlePointers (see gfx/pokemon/idle_pointers.asm)
// - BitmasksPointers (see gfx/pokemon/bitmask_pointers.asm)
// - FramesPointers (see gfx/pokemon/frame_pointers.asm)
// - EZChat_SortedPokemon (see data/pokemon/ezchat_order.asm)
enum {
    BULBASAUR = 1,
    IVYSAUR,
    VENUSAUR,
    CHARMANDER,
    CHARMELEON,
    CHARIZARD,
    SQUIRTLE,
    WARTORTLE,
    BLASTOISE,
    CATERPIE,
    METAPOD,
    BUTTERFREE,
    WEEDLE,
    KAKUNA,
    BEEDRILL,
    PIDGEY,
    PIDGEOTTO,
    PIDGEOT,
    RATTATA,
    RATICATE,
    SPEAROW,
    FEAROW,
    EKANS,
    ARBOK,
    PIKACHU,
    RAICHU,
    SANDSHREW,
    SANDSLASH,
    NIDORAN_F,
    NIDORINA,
    NIDOQUEEN,
    NIDORAN_M,
    NIDORINO,
    NIDOKING,
    CLEFAIRY,
    CLEFABLE,
    VULPIX,
    NINETALES,
    JIGGLYPUFF,
    WIGGLYTUFF,
    ZUBAT,
    GOLBAT,
    ODDISH,
    GLOOM,
    VILEPLUME,
    PARAS,
    PARASECT,
    VENONAT,
    VENOMOTH,
    DIGLETT,
    DUGTRIO,
    MEOWTH,
    PERSIAN,
    PSYDUCK,
    GOLDUCK,
    MANKEY,
    PRIMEAPE,
    GROWLITHE,
    ARCANINE,
    POLIWAG,
    POLIWHIRL,
    POLIWRATH,
    ABRA,
    KADABRA,
    ALAKAZAM,
    MACHOP,
    MACHOKE,
    MACHAMP,
    BELLSPROUT,
    WEEPINBELL,
    VICTREEBEL,
    TENTACOOL,
    TENTACRUEL,
    GEODUDE,
    GRAVELER,
    GOLEM,
    PONYTA,
    RAPIDASH,
    SLOWPOKE,
    SLOWBRO,
    MAGNEMITE,
    MAGNETON,
    FARFETCH_D,
    DODUO,
    DODRIO,
    SEEL,
    DEWGONG,
    GRIMER,
    MUK,
    SHELLDER,
    CLOYSTER,
    GASTLY,
    HAUNTER,
    GENGAR,
    ONIX,
    DROWZEE,
    HYPNO,
    KRABBY,
    KINGLER,
    VOLTORB,
    ELECTRODE,
    EXEGGCUTE,
    EXEGGUTOR,
    CUBONE,
    MAROWAK,
    HITMONLEE,
    HITMONCHAN,
    LICKITUNG,
    KOFFING,
    WEEZING,
    RHYHORN,
    RHYDON,
    CHANSEY,
    TANGELA,
    KANGASKHAN,
    HORSEA,
    SEADRA,
    GOLDEEN,
    SEAKING,
    STARYU,
    STARMIE,
    MR__MIME,
    SCYTHER,
    JYNX,
    ELECTABUZZ,
    MAGMAR,
    PINSIR,
    TAUROS,
    MAGIKARP,
    GYARADOS,
    LAPRAS,
    DITTO,
    EEVEE,
    VAPOREON,
    JOLTEON,
    FLAREON,
    PORYGON,
    OMANYTE,
    OMASTAR,
    KABUTO,
    KABUTOPS,
    AERODACTYL,
    SNORLAX,
    ARTICUNO,
    ZAPDOS,
    MOLTRES,
    DRATINI,
    DRAGONAIR,
    DRAGONITE,
    MEWTWO,
    MEW,
    CHIKORITA,
    BAYLEEF,
    MEGANIUM,
    CYNDAQUIL,
    QUILAVA,
    TYPHLOSION,
    TOTODILE,
    CROCONAW,
    FERALIGATR,
    SENTRET,
    FURRET,
    HOOTHOOT,
    NOCTOWL,
    LEDYBA,
    LEDIAN,
    SPINARAK,
    ARIADOS,
    CROBAT,
    CHINCHOU,
    LANTURN,
    PICHU,
    CLEFFA,
    IGGLYBUFF,
    TOGEPI,
    TOGETIC,
    NATU,
    XATU,
    MAREEP,
    FLAAFFY,
    AMPHAROS,
    BELLOSSOM,
    MARILL,
    AZUMARILL,
    SUDOWOODO,
    POLITOED,
    HOPPIP,
    SKIPLOOM,
    JUMPLUFF,
    AIPOM,
    SUNKERN,
    SUNFLORA,
    YANMA,
    WOOPER,
    QUAGSIRE,
    ESPEON,
    UMBREON,
    MURKROW,
    SLOWKING,
    MISDREAVUS,
    UNOWN,
    WOBBUFFET,
    GIRAFARIG,
    PINECO,
    FORRETRESS,
    DUNSPARCE,
    GLIGAR,
    STEELIX,
    SNUBBULL,
    GRANBULL,
    QWILFISH,
    SCIZOR,
    SHUCKLE,
    HERACROSS,
    SNEASEL,
    TEDDIURSA,
    URSARING,
    SLUGMA,
    MAGCARGO,
    SWINUB,
    PILOSWINE,
    CORSOLA,
    REMORAID,
    OCTILLERY,
    DELIBIRD,
    MANTINE,
    SKARMORY,
    HOUNDOUR,
    HOUNDOOM,
    KINGDRA,
    PHANPY,
    DONPHAN,
    PORYGON2,
    STANTLER,
    SMEARGLE,
    TYROGUE,
    HITMONTOP,
    SMOOCHUM,
    ELEKID,
    MAGBY,
    MILTANK,
    BLISSEY,
    RAIKOU,
    ENTEI,
    SUICUNE,
    LARVITAR,
    PUPITAR,
    TYRANITAR,
    LUGIA,
    HO_OH,
    CELEBI,
    EGG = 0xFD,
};

#define JOHTO_POKEMON CHIKORITA
#define NUM_POKEMON CELEBI

// Unown forms
// indexes for:
// - UnownWords (see data/pokemon/unown_words.asm)
// - UnownPicPointers (see data/pokemon/unown_pic_pointers.asm)
// - UnownAnimationPointers (see gfx/pokemon/unown_anim_pointers.asm)
// - UnownAnimationIdlePointers (see gfx/pokemon/unown_idle_pointers.asm)
// - UnownBitmasksPointers (see gfx/pokemon/unown_bitmask_pointers.asm)
// - UnownFramesPointers (see gfx/pokemon/unown_frame_pointers.asm)
enum {
    UNOWN_A = 1,
    UNOWN_B,
    UNOWN_C,
    UNOWN_D,
    UNOWN_E,
    UNOWN_F,
    UNOWN_G,
    UNOWN_H,
    UNOWN_I,
    UNOWN_J,
    UNOWN_K,
    UNOWN_L,
    UNOWN_M,
    UNOWN_N,
    UNOWN_O,
    UNOWN_P,
    UNOWN_Q,
    UNOWN_R,
    UNOWN_S,
    UNOWN_T,
    UNOWN_U,
    UNOWN_V,
    UNOWN_W,
    UNOWN_X,
    UNOWN_Y,
    UNOWN_Z,
};

#define NUM_UNOWN UNOWN_Z
