// wPrinterStatus
enum {
    PRINTER_STATUS_CHECKING,
    PRINTER_STATUS_TRANSMITTING,
    PRINTER_STATUS_PRINTING,
    PRINTER_ERROR_1,
    PRINTER_ERROR_2,
    PRINTER_ERROR_3,
    PRINTER_ERROR_4,
};
