// Tilesets indexes (see data/tilesets.asm)
enum {
    TILESET_JOHTO = 1,
    TILESET_JOHTO_MODERN,
    TILESET_KANTO,
    TILESET_BATTLE_TOWER_OUTSIDE,
    TILESET_HOUSE,
    TILESET_PLAYERS_HOUSE,
    TILESET_POKECENTER,
    TILESET_GATE,
    TILESET_PORT,
    TILESET_LAB,
    TILESET_FACILITY,
    TILESET_MART,
    TILESET_MANSION,
    TILESET_GAME_CORNER,
    TILESET_ELITE_FOUR_ROOM,
    TILESET_TRADITIONAL_HOUSE,
    TILESET_TRAIN_STATION,
    TILESET_CHAMPIONS_ROOM,
    TILESET_LIGHTHOUSE,
    TILESET_PLAYERS_ROOM,
    TILESET_POKECOM_CENTER,
    TILESET_BATTLE_TOWER_INSIDE,
    TILESET_TOWER,
    TILESET_CAVE,
    TILESET_PARK,
    TILESET_RUINS_OF_ALPH,
    TILESET_RADIO_TOWER,
    TILESET_UNDERGROUND,
    TILESET_ICE_PATH,
    TILESET_DARK_CAVE,
    TILESET_FOREST,
    TILESET_BETA_WORD_ROOM,
    TILESET_HO_OH_WORD_ROOM,
    TILESET_KABUTO_WORD_ROOM,
    TILESET_OMANYTE_WORD_ROOM,
    TILESET_AERODACTYL_WORD_ROOM,
};
#define NUM_TILESETS TILESET_AERODACTYL_WORD_ROOM

// wTileset struct size
#define TILESET_LENGTH 15

// roof length (see gfx/tilesets/roofs)
#define ROOF_LENGTH 9

// bg palette values (see gfx/tilesets/*_palette_map.asm)
// TilesetBGPalette indexes (see gfx/tilesets/bg_tiles.pal)
enum {
    PAL_BG_GRAY,    // 0
    PAL_BG_RED,     // 1
    PAL_BG_GREEN,   // 2
    PAL_BG_WATER,   // 3
    PAL_BG_YELLOW,  // 4
    PAL_BG_BROWN,   // 5
    PAL_BG_ROOF,    // 6
    PAL_BG_TEXT,    // 7
};
