// wInputType::
#define AUTO_INPUT 0xff

// wDebugFlags::
enum {
    DEBUG_BATTLE_F,
    DEBUG_FIELD_F,
};
// wCurDexMode::
enum {
    DEXMODE_NEW,
    DEXMODE_OLD,
    DEXMODE_ABC,
    DEXMODE_UNOWN,
};
// wMonType::
enum {
    PARTYMON,
    OTPARTYMON,
    BOXMON,
    TEMPMON,
    WILDMON,
};
// wGameTimerPaused::
#define GAME_TIMER_PAUSED_F 0
#define GAME_TIMER_MOBILE_F 7

// wJoypadDisable::
#define JOYPAD_DISABLE_MON_FAINT_F 6
#define JOYPAD_DISABLE_SGB_TRANSFER_F 7

// wOptions1::
#define TEXT_DELAY_MASK 0b111
enum {
    NO_TEXT_SCROLL = 4,
    STEREO = 5,
    BATTLE_SHIFT = 6,
    BATTLE_SCENE = 7,
};
#define TEXT_DELAY_FAST 0b001  // 1
#define TEXT_DELAY_MED 0b011   // 3
#define TEXT_DELAY_SLOW 0b101  // 5

// wTextboxFrame::
enum {
    FRAME_1,
    FRAME_2,
    FRAME_3,
    FRAME_4,
    FRAME_5,
    FRAME_6,
    FRAME_7,
    FRAME_8,
    NUM_FRAMES,
};

// wTextboxFlags::
enum {
    FAST_TEXT_DELAY_F,
    NO_TEXT_DELAY_F,
};
// wGBPrinterBrightness::
#define GBPRINTER_LIGHTEST 0x00
#define GBPRINTER_LIGHTER 0x20
#define GBPRINTER_NORMAL 0x40
#define GBPRINTER_DARKER 0x60
#define GBPRINTER_DARKEST 0x7f

// wOptions2::
enum {
    MENU_ACCOUNT = 0
};
// wWalkingDirection::
enum {
    STANDING = -1,
    DOWN,
    UP,
    LEFT,
    RIGHT,
    NUM_DIRECTIONS,
};

#define DOWN_MASK (1 << DOWN)
#define UP_MASK (1 << UP)
#define LEFT_MASK (1 << LEFT)
#define RIGHT_MASK (1 << RIGHT)

// wFacingDirection::
enum {
    FACE_DOWN = 8,
    FACE_UP = 4,
    FACE_LEFT = 2,
    FACE_RIGHT = 1,
};
#define FACE_CURRENT 0

// wPokemonWithdrawDepositParameter::
#define PC_WITHDRAW 0
#define PC_DEPOSIT 1
#define REMOVE_PARTY 0
#define REMOVE_BOX 1
#define DAY_CARE_WITHDRAW 2
#define DAY_CARE_DEPOSIT 3

// wPlayerStepFlags::
enum {
    PLAYERSTEP_MIDAIR_F = 4,
    PLAYERSTEP_CONTINUE_F = 5,
    PLAYERSTEP_STOP_F = 6,
    PLAYERSTEP_START_F = 7,
};

// wInitListType::
#define INIT_ENEMYOT_LIST 1
#define INIT_BAG_ITEM_LIST 2
#define INIT_OTHER_ITEM_LIST 3
#define INIT_PLAYEROT_LIST 4
#define INIT_MON_LIST 5

// wTimeOfDay::
enum {
    MORN_F,
    DAY_F,
    NITE_F,
    DARKNESS_F,
    NUM_DAYTIMES,
};

#define MORN (1 << MORN_F)
#define DAY (1 << DAY_F)
#define NITE (1 << NITE_F)
#define DARKNESS (1 << DARKNESS_F)

#define ANYTIME MORN | DAY | NITE

// wTimeOfDayPalset::
#define DARKNESS_PALSET ((DARKNESS_F << 6) | (DARKNESS_F << 4) | (DARKNESS_F << 2) | DARKNESS_F)

// wBattleAnimFlags::
enum {
    BATTLEANIM_STOP_F,
    BATTLEANIM_IN_SUBROUTINE_F,
    BATTLEANIM_IN_LOOP_F,
    BATTLEANIM_KEEPSPRITES_F,
};

// wPlayerSpriteSetupFlags::
#define PLAYERSPRITESETUP_FACING_MASK 0b11
#define PLAYERSPRITESETUP_FEMALE_TO_MALE_F 2
#define PLAYERSPRITESETUP_CUSTOM_FACING_F 5
#define PLAYERSPRITESETUP_SKIP_RELOAD_GFX_F 6
#define PLAYERSPRITESETUP_RESET_ACTION_F 7

// wPlayerGender::
#define PLAYERGENDER_FEMALE_F 0

// wMapStatus::
enum {
    MAPSTATUS_START,
    MAPSTATUS_ENTER,
    MAPSTATUS_HANDLE,
    MAPSTATUS_DONE,
};

// wMapEventStatus::
enum {
    MAPEVENTS_ON,
    MAPEVENTS_OFF,
};
// wScriptFlags::
#define SCRIPT_RUNNING 2

// wScriptMode::
enum {
    SCRIPT_OFF,
    SCRIPT_READ,
    SCRIPT_WAIT_MOVEMENT,
    SCRIPT_WAIT,
};

// wSpawnAfterChampion::
#define SPAWN_LANCE 1
#define SPAWN_RED 2

// wCurDay::
enum {
    SUNDAY,
    MONDAY,
    TUESDAY,
    WEDNESDAY,
    THURSDAY,
    FRIDAY,
    SATURDAY,
};

// wStatusFlags::
enum {
    STATUSFLAGS_POKEDEX_F,
    STATUSFLAGS_UNOWN_DEX_F,
    STATUSFLAGS_FLASH_F,
    STATUSFLAGS_CAUGHT_POKERUS_F,
    STATUSFLAGS_ROCKET_SIGNAL_F,
    STATUSFLAGS_NO_WILD_ENCOUNTERS_F,
    STATUSFLAGS_HALL_OF_FAME_F,
    STATUSFLAGS_MAIN_MENU_MOBILE_CHOICES_F,
};

// wStatusFlags2::
enum {
    STATUSFLAGS2_ROCKETS_IN_RADIO_TOWER_F,
    STATUSFLAGS2_SAFARI_GAME_F,
    STATUSFLAGS2_BUG_CONTEST_TIMER_F,
    STATUSFLAGS2_UNUSED_3_F,
    STATUSFLAGS2_BIKE_SHOP_CALL_F,
    STATUSFLAGS2_UNUSED_5_F,
    STATUSFLAGS2_REACHED_GOLDENROD_F,
    STATUSFLAGS2_ROCKETS_IN_MAHOGANY_F,
};

// wMomSavingMoney::
#define MOM_SAVING_SOME_MONEY_F 0
#define MOM_SAVING_HALF_MONEY_F 1
#define MOM_SAVING_ALL_MONEY_F 2
#define MOM_ACTIVE_F 7

#define MOM_SAVING_MONEY_MASK ((1 << MOM_SAVING_SOME_MONEY_F) | (1 << MOM_SAVING_HALF_MONEY_F) | (1 << MOM_SAVING_ALL_MONEY_F))

// wJohtoBadges::
enum {
    ZEPHYRBADGE,
    HIVEBADGE,
    PLAINBADGE,
    FOGBADGE,
    MINERALBADGE,
    STORMBADGE,
    GLACIERBADGE,
    RISINGBADGE,
    NUM_JOHTO_BADGES,
};

// wKantoBadges::
enum {
    BOULDERBADGE,
    CASCADEBADGE,
    THUNDERBADGE,
    RAINBOWBADGE,
    SOULBADGE,
    MARSHBADGE,
    VOLCANOBADGE,
    EARTHBADGE,
    NUM_KANTO_BADGES,
};
#define NUM_BADGES NUM_JOHTO_BADGES + NUM_KANTO_BADGES

// wPokegearFlags::
enum {
    POKEGEAR_MAP_CARD_F,
    POKEGEAR_RADIO_CARD_F,
    POKEGEAR_PHONE_CARD_F,
    POKEGEAR_EXPN_CARD_F,
    POKEGEAR_OBTAINED_F = 7
};
// wWhichRegisteredItem::
#define REGISTERED_POCKET 0b11000000
#define REGISTERED_NUMBER 0b00111111

// wPlayerState::
#define PLAYER_NORMAL 0
#define PLAYER_BIKE 1
#define PLAYER_SKATE 2
#define PLAYER_SURF 4
#define PLAYER_SURF_PIKA 8

// wCelebiEvent::
#define CELEBIEVENT_FOREST_IS_RESTLESS_F 2

// wBikeFlags::
enum {
    BIKEFLAGS_STRENGTH_ACTIVE_F,
    BIKEFLAGS_ALWAYS_ON_BIKE_F,
    BIKEFLAGS_DOWNHILL_F,
};
// wDailyFlags1::
enum {
    DAILYFLAGS1_KURT_MAKING_BALLS_F,
    DAILYFLAGS1_BUG_CONTEST_F,
    DAILYFLAGS1_FISH_SWARM_F,
    DAILYFLAGS1_TIME_CAPSULE_F,
    DAILYFLAGS1_ALL_FRUIT_TREES_F,
    DAILYFLAGS1_GOT_SHUCKIE_TODAY_F,
    DAILYFLAGS1_GOLDENROD_UNDERGROUND_BARGAIN_F,
    DAILYFLAGS1_TRAINER_HOUSE_F,
};
// wDailyFlags2::
enum {
    DAILYFLAGS2_MT_MOON_SQUARE_CLEFAIRY_F,
    DAILYFLAGS2_UNION_CAVE_LAPRAS_F,
    DAILYFLAGS2_GOLDENROD_UNDERGROUND_GOT_HAIRCUT_F,
    DAILYFLAGS2_GOLDENROD_DEPT_STORE_TM27_RETURN_F,
    DAILYFLAGS2_DAISYS_GROOMING_F,
    DAILYFLAGS2_INDIGO_PLATEAU_RIVAL_FIGHT_F,
    DAILYFLAGS2_MOVE_TUTOR_F,
    DAILYFLAGS2_BUENAS_PASSWORD_F,
};

// wSwarmFlags::
enum {
    SWARMFLAGS_BUENAS_PASSWORD_F,
    SWARMFLAGS_GOLDENROD_DEPT_STORE_SALE_F,
    SWARMFLAGS_DUNSPARCE_SWARM_F,
    SWARMFLAGS_YANMA_SWARM_F,
    SWARMFLAGS_MOBILE_4_F,
};

// wLuckyNumberShowFlag::
#define LUCKYNUMBERSHOW_GAME_OVER_F 0

// wDayCareMan::
#define DAYCAREMAN_HAS_MON_F 0
#define DAYCAREMAN_MONS_COMPATIBLE_F 5
#define DAYCAREMAN_HAS_EGG_F 6
#define DAYCAREMAN_ACTIVE_F 7

// wDayCareLady::
#define DAYCARELADY_HAS_MON_F 0
#define DAYCARELADY_ACTIVE_F 7
