#include "constants.h"

// SECTION "NULL", ROM0
// NULL::

#include "home/header.h"

// SECTION "Home", ROM0

#include "home/init.h"
#include "home/vblank.h"
#include "home/delay.h"
#include "home/time_palettes.h"
#include "home/fade.h"
#include "home/lcd.h"
#include "home/time.h"
#include "home/serial.h"
#include "home/joypad.h"
#include "home/decompress.h"
#include "home/palettes.h"
#include "home/gfx.h"
#include "home/text.h"
#include "home/video.h"
#include "home/map_objects.h"
#include "home/sine.h"
#include "home/movement.h"
#include "home/menu.h"
#include "home/printer.h"
#include "home/game_time.h"
//#include "home/map.h"
#include "home/farcall.h"
#include "home/predef.h"
#include "home/window.h"
#include "home/flag.h"
#include "home/sprite_updates.h"
#include "home/string.h"
#include "home/region.h"
#include "home/item.h"
#include "home/random.h"
//#include "home/sram.h"
#include "home/call_regs.h"
#include "home/double_speed.h"
#include "home/clear_sprites.h"
#include "home/copy.h"
#include "home/copy_tilemap.h"
#include "home/copy_name.h"
#include "home/array.h"
#include "home/math.h"
#include "home/print_text.h"
#include "home/queue_script.h"
#include "home/compare.h"
#include "home/tilemap.h"
#include "home/pokedex_flags.h"
#include "home/names.h"
#include "home/scrolling_menu.h"
#include "home/stone_queue.h"
#include "home/trainers.h"
#include "home/pokemon.h"
#include "home/print_bcd.h"
#include "home/battle.h"
#include "home/sprite_anims.h"
#include "home/audio.h"
#include "home/mobile.h"