//#include "macros/asserts.h"
//#include "macros/const.h"
//#include "macros/predef.h"
//#include "macros/rst.h"
//#include "macros/data.h"
//#include "macros/code.h"
#include "macros/gfx.h"
#include "macros/coords.h"

#include "macros/scripts/audio.h"
//#include "macros/scripts/maps.h"
//#include "macros/scripts/events.h"
#include "macros/scripts/text.h"
#include "macros/scripts/movement.h"
//#include "macros/scripts/battle_commands.h"
//#include "macros/scripts/battle_anims.h"
//#include "macros/scripts/gfx_anims.h"

//#include "macros/legacy.h"
