SECTION "VRAM0", VRAM

vTiles0:: ds $80 * LEN_2BPP_TILE
vTiles1:: ds $80 * LEN_2BPP_TILE
vTiles2:: ds $80 * LEN_2BPP_TILE
vBGMap0:: ds BG_MAP_WIDTH * BG_MAP_HEIGHT
vBGMap1:: ds BG_MAP_WIDTH * BG_MAP_HEIGHT


SECTION "VRAM1", VRAM

vTiles3:: ds $80 * LEN_2BPP_TILE
vTiles4:: ds $80 * LEN_2BPP_TILE
vTiles5:: ds $80 * LEN_2BPP_TILE
vBGMap2:: ds BG_MAP_WIDTH * BG_MAP_HEIGHT
vBGMap3:: ds BG_MAP_WIDTH * BG_MAP_HEIGHT
