char IsAPokemon(char wCurPartySpecies);
void DrawBattleHPBar(void);
void PrepMonFrontpic(void);
void v_PrepMonFrontpic(void);
void PlayStereoCry(void);
void PlayStereoCry2(void);
void PlayMonCry(void);
void PlayMonCry2(void);
void v_PlayMonCry(void);
void LoadCry(void);
void GetCryIndex(void);
void PrintLevel(void);
void PrintLevel_Force3Digits(void);
void Print8BitNumLeftAlign(void);
void GetNthMove(void);
void GetBaseData(void);
void GetCurNickname(void);
void GetNickname(void);
