#include "../constants.h"
#include "random.h"

void Random(void){
    //  A simple hardware-based random number generator (RNG).

//  Two random numbers are generated by adding and subtracting
//  the divider to the respective values every time it's called.

//  The divider is a register that increments at a rate of 16384Hz.
//  For comparison, the Game Boy operates at a clock speed of 4.2MHz.

//  Additionally, an equivalent function is executed in VBlank.

//  This leaves a with the value in hRandomSub.

    PUSH_BC;

    LDH_A_addr(rDIV);
    LD_B_A;
    LDH_A_addr(hRandomAdd);
    ADC_A_B;
    LDH_addr_A(hRandomAdd);

    LDH_A_addr(rDIV);
    LD_B_A;
    LDH_A_addr(hRandomSub);
    SBC_A_B;
    LDH_addr_A(hRandomSub);

    POP_BC;
    RET;

}

void BattleRandom(void){
    //  _BattleRandom lives in another bank.

//  It handles all RNG calls in the battle engine, allowing
//  link battles to remain in sync using a shared PRNG.

    LDH_A_addr(hROMBank);
    PUSH_AF;
    LD_A(BANK(av_BattleRandom));
    RST(aBankswitch);

    CALL(av_BattleRandom);

    LD_addr_A(wPredefHL + 1);
    POP_AF;
    RST(aBankswitch);
    LD_A_addr(wPredefHL + 1);
    RET;

}

void RandomRange(void){
    //  Return a random number between 0 and a (non-inclusive).

    PUSH_BC;
    LD_C_A;

// b = $100 % c
    XOR_A_A;
    SUB_A_C;

mod:
        SUB_A_C;
    IF_NC goto mod;
    ADD_A_C;
    LD_B_A;

// Get a random number
// from 0 to $ff - b.
    PUSH_BC;

loop:
        CALL(aRandom);
    LDH_A_addr(hRandomAdd);
    LD_C_A;
    ADD_A_B;
    IF_C goto loop;
    LD_A_C;
    POP_BC;

    CALL(aSimpleDivide);

    POP_BC;
    RET;

}
